### PR TITLE
IPv6-support

### PR DESCRIPTION
**Pull request by bmarwell**
- Added IPv6 support (incomplete)
- Only set last touple of IPv4 to null. This is fine even for german
  concerns.

### CODE REVIEW

**Comment by bmarwell** [comment]
As I am on IPv6 already (tunnelbroker.net) this is a concern to me. Also, this is the very first thing I did on github, I hope I did it all correctly!

I changed the privacy thing to the last touple, as it is being done in Piwik as well. This is more than sufficient, isn't it?

**Comment by sas101** [comment]
Looks good! Thank you for your contribution!

With "incomplete" do you mean in regard to your comment about ::ffff:127.0.0.1?

I understand the problem is in general with this type of dotted-quad notation, because there can be any kind of IPv4 address at the end, not only localhost. Is that true?
If that's the case, I suspect we should handle that special case.
Although I intend to keep the function as fast as possible.

I agree that removing the last tuple of the IPv4 address is more than enough.

**Comment by bmarwell** [comment]
Hi,

yes, you can always have an IPv4 address at the end of IPv6 addresses. But the change I made might still be sufficient, as the part behind the last colon still is being nulled. Therefore it might not be neccessary to handle this special case.

I agree that this pseudonymize-plugin should stay as simple as possible.

**Comment by bmarwell** [comment]
PS: This pushes the PHP requirement to PHP >= 5.2.0.
http://php.net/manual/en/function.filter-var.php

**Comment by sas101** [comment]
OK, I merged it now.

Will add some simple tests, because I think it will null out the whole IPv4 address at the end of an IPv6 address, thus leaving us with ::ffff:0
Then we'll see..

**Comment by sas101** [comment]
Indeed my tests show, that the whole IPv4 address is removed.
Checking ::ffff:127.0.0.1 => ::ffff:127.0.0.0 ? ... FAILED - was ::ffff:0
Checking ::ffff:192.0.43.10 => ::ffff:192.0.43.0 ? ... FAILED - was ::ffff:0
see the bug report #2

**Pull request merged**
